export const GN_LAYER_REVISION_KEY: string = 'gnLayerRevision';
export const GN_MULTI_MAP_LINK_ENABLED_KEY: string = 'gnMultiMapLinkEnabled';
export const GN_MULTI_MAP_VIEWPORT_REVISION_KEY: string = 'gnMultiMapViewportRevision';
export const GN_MULTI_MAP_VIEWPORT_CENTER_X_KEY: string = 'gnMultiMapViewportCenterX';
export const GN_MULTI_MAP_VIEWPORT_CENTER_Y_KEY: string = 'gnMultiMapViewportCenterY';
export const GN_MULTI_MAP_VIEWPORT_SCALE_KEY: string = 'gnMultiMapViewportScale';
export const GN_MULTI_MAP_VIEWPORT_SOURCE_KEY: string = 'gnMultiMapViewportSource';
